const words = [
  { id: 1, japanese: "みかん", variations: ["mikan"] },
  { id: 2, japanese: "りんご", variations: ["ringo", "rinngo"] },
  { id: 3, japanese: "いちご", variations: ["ichigo", "itigo"] },
  { id: 4, japanese: "パイナップル", variations: ["painappuru", "painaltupuru"] },
  { id: 5, japanese: "オレンジ", variations: ["orenji", "orennji", "orenzi", "orennzi"] },
  { id: 6, japanese: "さくらんぼ", variations: ["sakuranbo", "sakurannbo", "saquranbo", "saqurannbo"] },
  { id: 7, japanese: "フルーツ全種類盛り合わせ", variations: ["huru-tsuzennsyuruimoriawase", "huru-tuzennsyuruimoriawase", "huru-tsuzensyuruimoriawase", "huru-tsuzennsilyuruimoriawase", "huru-tuzennsilyuruimoriawase", "huru-tuzensilyuruimoriawase", "furu-tsuzennsyuruimoriawase", "furu-tuzennsyuruimoriawase", "furu-tsuzensyuruimoriawase", "furu-tsuzennsilyuruimoriawase", "furu-tsuzensilyuruimoriawase", "furu-tuzensyuruimoriawase", "huru-tuzensyuruimoriawase"] },
  { id: 8, japanese: "天ぷら", variations: ["tenpura", "tennpura"] },
  { id: 9, japanese: "ラーメン", variations: ["ra-men"] },
  { id: 10, japanese: "たこ焼き", variations: ["takoyaki"] },
  { id: 11, japanese: "餃子", variations: ["gyouza"] },
  { id: 12, japanese: "カレーライス", variations: ["kare-raisu"] },
  { id: 13, japanese: "ハンバーグ", variations: ["hanba-gu", "hannba-gu"] },
  { id: 14, japanese: "猫", variations: ["neko"] },
  { id: 15, japanese: "犬", variations: ["inu"] },
  { id: 16, japanese: "キリン", variations: ["kirin"] },
  { id: 17, japanese: "ペンギン", variations: ["pengin", "penngin"] },
  { id: 18, japanese: "ライオン", variations: ["raion"] },
  { id: 19, japanese: "ゴリラ", variations: ["gorira"] },
  { id: 20, japanese: "東京", variations: ["toukyou", "toukilyou"] },
  { id: 21, japanese: "大阪", variations: ["oosaka"] },
  { id: 22, japanese: "京都", variations: ["kyouto", "kilyouto"] },
  { id: 23, japanese: "札幌", variations: ["sapporo", "saltuporo"] },
  { id: 24, japanese: "横浜", variations: ["yokohama"] },
  { id: 25, japanese: "福岡", variations: ["hukuoka", "fukuoka"] },
  { id: 26, japanese: "自転車", variations: ["jitensya", "zitensya", "jitennsya", "zitennsya", "jitensilya", "zitensilya", "jitennsilya", "zitennsilya"] },
  { id: 27, japanese: "バス", variations: ["basu"] },
  { id: 28, japanese: "電車", variations: ["densya", "dennsya", "densilya", "dennsilya"] },
  { id: 29, japanese: "飛行機", variations: ["hikouki"] },
  { id: 30, japanese: "新幹線", variations: ["shinkansen", "sinkansen", "shinnkansen", "sinnkansen", "shinkannsen", "sinkannsen", "shinnkannsen", "sinnkannsen"] },
  { id: 31, japanese: "ヘリコプター", variations: ["herikoputa-"] },
  { id: 32, japanese: "タクシー", variations: ["takushi-", "taqushi-", "takusi-", "taqusi-"] },
];

export default words;