const words = [
  { id: 1, japanese: "みかん", variations: ["mikan"] },
  { id: 2, japanese: "りんご", variations: ["ringo", "rinngo"] },
  { id: 3, japanese: "いちご", variations: ["ichigo", "itigo"] },
  { id: 4, japanese: "パイナップル", variations: ["painappuru", "painaltupuru"] },
  { id: 5, japanese: "オレンジ", variations: ["orenji", "orennji", "orenzi", "orennzi"] },
  { id: 6, japanese: "さくらんぼ", variations: ["sakuranbo", "sakurannbo", "saquranbo", "saqurannbo"] },
  { id: 7, japanese: "フルーツ全種類盛り合わせ", variations: ["huru-tsuzennsyuruimoriawase", "huru-tuzennsyuruimoriawase", "huru-tsuzensyuruimoriawase", "huru-tsuzennsilyuruimoriawase", "huru-tuzennsilyuruimoriawase", "huru-tuzensilyuruimoriawase", "furu-tsuzennsyuruimoriawase", "furu-tuzennsyuruimoriawase", "furu-tsuzensyuruimoriawase", "furu-tsuzennsilyuruimoriawase", "furu-tsuzensilyuruimoriawase", "furu-tuzensyuruimoriawase", "huru-tuzensyuruimoriawase", "furu-tuzensilyuruimoriawase", "furu-tuzennsilyuruimoriawase"] },
  { id: 8, japanese: "天ぷら", variations: ["tenpura", "tennpura"] },
  { id: 9, japanese: "ラーメン", variations: ["ra-men"] },
  { id: 10, japanese: "たこ焼き", variations: ["takoyaki"] },
  { id: 11, japanese: "餃子", variations: ["gyouza"] },
  { id: 12, japanese: "カレーライス", variations: ["kare-raisu"] },
  { id: 13, japanese: "ハンバーグ", variations: ["hanba-gu", "hannba-gu"] },
  { id: 14, japanese: "猫", variations: ["neko"] },
  { id: 15, japanese: "犬", variations: ["inu"] },
  { id: 16, japanese: "キリン", variations: ["kirin"] },
  { id: 17, japanese: "ペンギン", variations: ["pengin", "penngin"] },
  { id: 18, japanese: "ライオン", variations: ["raion"] },
  { id: 19, japanese: "ゴリラ", variations: ["gorira"] },
  { id: 20, japanese: "東京", variations: ["toukyou", "toukilyou"] },
  { id: 21, japanese: "大阪", variations: ["oosaka"] },
  { id: 22, japanese: "京都", variations: ["kyouto", "kilyouto"] },
  { id: 23, japanese: "札幌", variations: ["sapporo", "saltuporo"] },
  { id: 24, japanese: "横浜", variations: ["yokohama"] },
  { id: 25, japanese: "福岡", variations: ["hukuoka", "fukuoka"] },
  { id: 26, japanese: "自転車", variations: ["jitensya", "zitensya", "jitennsya", "zitennsya", "jitensilya", "zitensilya", "jitennsilya", "zitennsilya"] },
  { id: 27, japanese: "バス", variations: ["basu"] },
  { id: 28, japanese: "電車", variations: ["densya", "dennsya", "densilya", "dennsilya"] },
  { id: 29, japanese: "飛行機", variations: ["hikouki"] },
  { id: 30, japanese: "新幹線", variations: ["shinkansen", "sinkansen", "shinnkansen", "sinnkansen", "shinkannsen", "sinkannsen", "shinnkannsen", "sinnkannsen"] },
  { id: 31, japanese: "ヘリコプター", variations: ["herikoputa-"] },
  { id: 32, japanese: "タクシー", variations: ["takushi-", "taqushi-", "takusi-", "taqusi-"] },
  { id: 33, japanese: "国際連合", variations: ["kokusairengou", "koqusairengou", "kokusairenngou", "koqusairenngou"] },
  { id: 34, japanese: "人工知能", variations: ["jinkouchinou", "zinkouchinou", "jinnkouchinou", "zinnkouchinou", "jinkoutinou", "zinkoutinou", "jinnkoutinou", "zinnkoutinou"] },
  { id: 35, japanese: "電気工学", variations: ["denkikougaku", "dennkikougaku"] },
  { id: 36, japanese: "自動販売機", variations: ["jidouhanbaiki", "zidouhanbaiki", "jidouhannbaiki", "zidouhannbaiki"] },
  { id: 37, japanese: "宿題が終わらない", variations: ["syukudaigaowaranai", "shukudaigaowaranai", "silyukudaigaowaranai", "syuqudaigaowaranai", "shuqudaigaowaranai", "silyukudaigaowaranai"] },
  { id: 38, japanese: "明日は早起きしよう", variations: ["ashitahahayaokishiyou", "asitahahayaokishiyou", "ashitahahayaokisiyou", "asitahahayaokisiyou"] },
  { id: 39, japanese: "新しい本を買いました", variations: ["atarashiihonwokaimashita", "atarasiihonwokaimashita", "atarashiihonnwokaimashita", "atarasiihonnwokaimashita", "atarashiihonnwokaimasita", "atarasiihonnwokaimasita", "atarashiihonwokaimasita", "atarasiihonwokaimasita"] },
  { id: 40, japanese: "友達と映画を見に行く", variations: ["tomodachitoeigawominiiku", "tomodatitoeigawominiiku", "tomodachitoeigawominiiqu", "tomodatitoeigawominiiqu"] },
  { id: 41, japanese: "この曲の歌詞が好き", variations: ["konokyokunokashigasuki", "konokilyokunokashigasuki", "konokyokunokasigasuki", "konokilyokunokasigasuki", "konokyoqunokashigasuki", "konokyoqunokasigasuki", "konokilyoqunokasigasuki"] },
  { id: 42, japanese: "スマホの充電が切れそう", variations: ["sumahonojuudengakiresou", "sumahonozyuudengakiresou"] },
  { id: 43, japanese: "今日は早く寝るつもり", variations: ["kyouhahayakunerutumori", "kilyouhahayakunerutumori", "kyouhahayaqunerutumori", "kyouhahayakunerutsumori", "kilyouhahayaqunerutsumori", "kilyouhahayaqunerutumori", "kilyouhahayakunerutsumori"] },
  { id: 44, japanese: "スーパーで卵を買った", variations: ["su-pa-detamagowokatta", "su-pa-detamagowokaltuta"] },
  { id: 45, japanese: "財布を家に忘れた", variations: ["saihuwoieniwasureta", "saifuwoieniwasureta"] },
  { id: 46, japanese: "電車が遅れている", variations: ["densyagaokureteiru", "dennsyagaokureteiru", "densilyagaokureteiru", "densilyagaoqurteiru", "dennsyagaoqureteiru", "dennsilyagaoqureteiru", "dennsilyagaokureteiru"] },
  { id: 47, japanese: "今日は風が強い", variations: ["kyouhakazegatsuyoi", "kilyouhakazegatsuyoi", "kyouhakazegatuyoi", "kilyouhakazegatuyoi"] },
  { id: 48, japanese: "冬の朝は寒い", variations: ["huyunoasahasamui", "fuyunoasahasamui"] },
  { id: 49, japanese: "夏休みが楽しみです", variations: ["natsuyasumigatanoshimidesu", "natuyasumigatanoshimidesu", "natsuyasumigatanosimidesu", "natuyasumigatanosimidesu"] },
  { id: 50, japanese: "秋の夜は涼しい", variations: ["akinoyoruhasuzushii", "akinoyoruhasuzusii"] },
  { id: 51, japanese: "夕立が降りそうだ", variations: ["yuudachigahurisouda", "yuudatigahurisouda", "yuudachigafurisouda", "yuudatigafurisouda"] },
  { id: 52, japanese: "虹が綺麗に見えた", variations: ["nijigakireinimieta", "nizigakireinimieta"] },
  { id: 53, japanese: "初雪が降りました", variations: ["hatsuyukigahurimashita", "hatuyukigahurimasita", "hatsuyukigafurimasita", "hatuyukigafurimasita", "hatsuyukigahurimashita", "hatsuyukigahurimasita", "hatuyukigafurimashita"] },
  { id: 54, japanese: "台風が近づいている", variations: ["taihuugachikaduiteiru", "taifuugachikaduiteiru", "taihuugatikaduiteiru", "taifuugatikaduiteiru"] },
];

export default words;